In [5]:
import base64
import pandas as pd
import numpy as np

In [6]:
def create_onedrive_directdownload(onedrive_link):
    data_bytes64 = base64.b64encode(bytes(onedrive_link, 'utf-8'))
    data_bytes64_String = data_bytes64.decode('utf-8').replace('/','_').replace('+','-').rstrip("=")
    resultUrl = f"https://api.onedrive.com/v1.0/shares/u!{data_bytes64_String}/root/content"
    return resultUrl

In [7]:
onedrive_link='https://1drv.ms/x/s!AoiE7xOoBAsngsgjcYJ-9Gc78L96rg?e=X3Nujh'
onedrive_direct_link=create_onedrive_directdownload(onedrive_link)
onedrive_direct_link

'https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3gvcyFBb2lFN3hPb0JBc25nc2dqY1lKLTlHYzc4TDk2cmc_ZT1YM051amg/root/content'

In [8]:
df=pd.read_csv(onedrive_direct_link)
df

              personnel      product collaboration      legal
0                 staff      product          deal        law
1             employees     products           m&a    lawsuit
2             workforce    offerings   collaborate      legal
3               workers        goods        merged       fine
4                labour  merchandise      acquired  vergleich
..                  ...          ...           ...        ...
56           applicants          NaN           NaN        NaN
57  Personalentwicklung          NaN           NaN        NaN
58   Beschäftigungsrate          NaN           NaN        NaN
59             Kollegen          NaN           NaN        NaN
60          Arbeitsteam          NaN           NaN        NaN

[61 rows x 4 columns]

In [43]:
df.columns

Index(['_id', '_index', '_score', '_type', 'concepts', 'found_dates', 'id',
       'internal_links', 'keywords', 'language', 'news_author', 'news_content',
       'news_date', 'news_label', 'news_last_updated', 'news_legalinforce',
       'news_link', 'news_rank', 'news_summary', 'news_title', 'news_topic',
       'news_type', 'references', 'sentiment_label', 'sentiment_score',
       'source_country', 'source_name', 'source_type'],
      dtype='object')

In [47]:
df['news_label'].unique()

array([nan, 'curated'], dtype=object)

In [45]:
df.drop(['_index','_score','_type','concepts','id','internal_links','news_author','news_last_updated','news_legalinforce','news_link','references','source_name'],axis=1,inplace=True)
df

,_id,found_dates,keywords,language,news_content,news_date,news_label,news_rank,news_summary,news_title,news_topic,news_type,sentiment_label,sentiment_score,source_country,source_type
0,FinenfreiPresostenfrei12884764,[],NaN,de,The article discusses how a fortunate man with...,2023-10-03T18:00:43.000Z,NaN,0,The article discusses how a fortunate man with...,Tradingaktion mit comdirect Handeln Sie Socié...,"[{""description"":""Online Banken und Vermögensve...",Press releases,NaN,0.0,Germany,Information Provider
1,focScholzPresid217207826html,[],NaN,en,The article discusses how M.M. Warburg may hav...,2023-10-03T16:59:33.000Z,NaN,0,The article discusses how M.M. Warburg may hav...,CumExAffäre: Brisante Tagebucheinträge belaste...,"[{""description"":""M.M. Warburg"",""relevance"":12,...",Press releases,NaN,0.0,Global,Information Provider
2,merngnisPresente92556026html,[],NaN,en,The Cologne Prosecutor's Office accuses German...,2023-10-03T16:06:01.000Z,NaN,0,The Cologne Prosecutor's Office accuses German...,CumExAffäre: Dokumente bringen Scholz offenbar...,"[{""description"":""M.M. Warburg"",""relevance"":6,""...",Press releases,NaN,0.0,Global,Information Provider
3,maretBeatPresfiling20231003,[],NaN,en,Deutsche Bank AG has acquired an additional 49...,2023-10-03T15:45:10.000Z,NaN,0,Deutsche Bank AG has acquired an additional 49...,K.J. Harrison & Partners Inc Boosts Stake in C...,"[{""description"":""Deutsche Bank"",""relevance"":6,...",Press releases,NaN,0.0,Global,Information Provider
4,AlllationPres202310030398html,[],NaN,en,Mozambique has reached a negotiated agreement ...,2023-10-03T15:40:05.000Z,NaN,0,Mozambique has reached a negotiated agreement ...,Mozambique: Govt Wins Massive Debt Cancellation,"[{""description"":""Financial Crime"",""relevance"":...",Press releases,NaN,0.0,Africa,Information Provider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4766,berWochePresommerzbanka382003,[],NaN,de,Commerzbank: In Friedrichshagen hat ein neuer ...,2023-05-24T14:51:50.000Z,NaN,0,Commerzbank: In Friedrichshagen hat ein neuer ...,Neu eröffnet: Commerzbank Friedrichshagen Be...,"[{""description"":""Commerzbank AG"",""relevance"":2...",Press releases,NaN,0.0,Global,Information Provider
4767,finztreffStocuebergeben319151,[],NaN,de,Der DAX hat am Freitag ein neues Rekordhoch er...,2023-05-24T14:44:04.000Z,NaN,0,Der DAX hat am Freitag ein neues Rekordhoch er...,ROUNDUP: AirbusJubiläum in Hamburg 600. Flugz...,"[{""description"":""Commerzbank AG"",""relevance"":6...",Stock Analysis,NaN,0.0,Global,Information Provider
4768,boersedeStocageLinie34924557,[],NaN,de,Mit dem Rücksetzer auf 990 EUR hat die Commerz...,2023-05-24T14:41:30.000Z,NaN,0,Mit dem Rücksetzer auf 990 EUR hat die Commerz...,CommerzbankAktie unter 38TageLinie boerse.de,"[{""description"":""Commerzbank AG"",""relevance"":2...",Stock Analysis,NaN,0.0,Global,Information Provider
4769,monneywebPrestrustagencysays,[],NaN,en,The Competition and Markets Authority said Cit...,2023-05-24T14:38:58.000Z,NaN,0,The Competition and Markets Authority said Cit...,Five major banks colluded on UK bonds antitrus...,"[{""description"":""Deutsche Bank"",""relevance"":6,...",Press releases,NaN,0.0,Global,Information Provider
4770,ftgsaysPresb48f0f767522d802,[],NaN,en,Follow the topics in this article. Gilts. Add ...,2023-05-24T14:35:08.000Z,NaN,0,Follow the topics in this article. Gilts. Add ...,Five banks broke competition law over UK gover...,"[{""description"":""Compliance"",""relevance"":6,""co...",Press releases,NaN,0.0,Global,Information Provider